### ISSUE TITLE
require bug

### ISSUE THREAD

**Issue by stefan022** [aleksandarLazic1998/query-builder#1]
The problem arises when an attempt is made to require.

**Comment by aleksandarLazic1998** [comment]
@stefan022 Could you attach image of a error console?

**Comment by stefan022** [comment]
@aleksandarLazic1998 Here's the picture
Link: https://i.ibb.co/rcdz9w6/query-builder-al.png

**Comment by aleksandarLazic1998** [comment]
@stefan022 New version is pushed can you check if it is working now?

**Comment by stefan022** [comment]
@aleksandarLazic1998 It works!

Change your documentation, as it's necessary to destructure the import of the "queryBuilder":
`const { queryBuilder } = require('query-builder-al');`

Good job!

**Comment by aleksandarLazic1998** [comment]
@stefan022 Thank you for the detailed information's, does it works with "import" statement also?

**Comment by stefan022** [comment]
@aleksandarLazic1998 Yes, it works as well

**Comment by aleksandarLazic1998** [comment]
Then this issue is closed
